### ISSUE TITLE
Delete 1st section when multiple are present

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#119]
For example under software descriptions you can add new ones by hitting the create new button. All subsequent descriptions have the create new, duplicate and delete buttons, but the first section never has a delete option. It could be modified so that when multiple descriptions are present the first one can be deleted. This behavior would then be similar to the "-" boxes, where you can delete any of the sections so long as one is present.
![2](https://user-images.githubusercontent.com/44450691/55650513-868e2f00-57ab-11e9-9821-5ba6709df367.png)

**Comment by rsiegl** [comment]
Along with this should the Chemical shift reference section be deletable when only one is present? I am just not sure if this is a required section or not.
![3](https://user-images.githubusercontent.com/44450691/55650592-c35a2600-57ab-11e9-8b8c-41019e8df59c.png)

**Comment by jonwedell** [comment]
@elulrich - The assigned chemical shift reference section only appears if they have uploaded chemical shifts. If that is the case, should it be mandatory? If so, can you update the dictionary?

**Comment by elulrich** [comment]
The assigned chemical shift reference section should be mandatory if the depositor uploads assigned chemical shifts. The dictionary has the chemical shift reference fields set to 'Y' in the view mode. In addition the tags are listed as 'M' or 'V' in the Pulic validate. I am not sure where else to make this section and the appropriate fields mandatory.

**Comment by rsiegl** [comment]
A lot of the other sections I am used to seeing in every entry can also be deleted even though I feel as though most, if not all, of them are mandatory.  This includes Sample descriptions, Sample conditions, NMR spectrometers, NMR experimental descriptions and all the data sections (Heteronuclear NOEs, Heteronuclear T1 data, Heteronuclear T2 data, Order parameters and Assigned chemical shifts).

**Comment by jonwedell** [comment]
@elulrich - What Richard and I are referring to is the `mandatory_number` value from `adit_cat_grp_o.csv`. It must be set to a non-zero number, otherwise the `delete` button will appear for the saveframe.

**Comment by elulrich** [comment]
Ok, This seems to be a change from the way ADIT-NMR worked, I guess. 
Chem_shift_reference should only appear when any of 
assigned_chemical_shifts, theoretical_chem_shifts, and probably 
spectral_peak_list are uploaded.

What happens if someone uploads coupling_constants? Will the depositor 
be able to delete the save_frame? Assuming this is the case, I have set 
the number to '1' for all of the MC and M categories.

**Comment by jonwedell** [comment]
I just checked, and chem_shift_reference only appears for uploaded assigned chemical shifts, and not for peak lists or theoretical chemical shifts. Does that need to be changed?

The coupling constants section only appears once they select that they have uploaded coupling constants. Should coupling constants saveframe be required if they upload this data? If so, then yes, `mandatory_number` should be 1. If this section can be deleted, then please set it to zero. Keeping in mind it will only appear in the first place if coupling constants are uploaded. This may indeed be different than ADIT.

Thanks!

**Comment by elulrich** [comment]
Yes, chem_shift_reference should appear for those other kinds of data. I 
wonder if this change may affect the validation software?

**Comment by elulrich** [comment]
Just updated git.

**Comment by jonwedell** [comment]
I can check with Dimitri if he expects that this will affect the validation software.

I can confirm your changes worked as expected, thanks.

I will add new override rules for spectral peak lists and theoretical chemical shifts.

**Comment by dmaziuk** [comment]
It won't if we don't update validation dictionary. 

I'm not sure I understand the problem: entry information is mandatory and can't be deleted, NMR spectrometer is not (you could have a SAX-only entry), so it can be. This is why overrides are there: if you're depositing NMR data then NMR spectrometer becomes mandatory. If you change your mind and delete all uploaded NMR data, NMR spectrometer becomes non-mandatory again.

Why do you need to optional sections mandatory up front?

**Comment by dmaziuk** [comment]
Part of the deal with ADIT is no undo button: if you delete a mandatory section, you have to re-type it all in later. If you have an undelete button, why not just let them delete anything they want?

That is orthogonal to having a state object that keeps track of overrides currently in force and is updated every time they hit save -- so that it can show the red exclamation marks in the sidebar so they know what they need to fill in.

**Comment by jonwedell** [comment]
> Part of the deal with ADIT is no undo button: if you delete a mandatory section, you have to re-type it all in later. If you have an undelete button, why not just let them delete anything they want?

You can't allow them to delete a "mandatory" section - unless you just immediately re-create the saveframe, but without values. (More of a "wipe" than a delete.) I think this is what ADIT does. It isn't a good user experience to require them to go undelete something that we should have never let them delete in the first place. (Why have a button that does nothing but make the entry invalid?)

Here is the flow of what happens:

1. Saveframes are shown or hidden based on whether or not any of their tags are visible (mandatory or optional)
2. If `mandatory_number` is >1 then the saveframe(s), *if shown*, cannot be deleted. The reason this is used, as opposed to just calculating it based on whether or not all tags are optional, is that it prevents the situation you are describing where they delete a section which later becomes mandatory. By having `mandatory_number` mean "if visible, it is mandatory" this problem is averted.

For saveframes like nmr spectrometer, the `mandatory_number` 0 allows them to be deleted, as they are always shown. (@elulrich, you changed the mandatory number of nmr spectrometer to 1 with the rest of your changes, that one should remain 0.)

Finally, saveframes with all optional tags, so long as they are visible, are spit out with the final deposition. Deleted saveframes are not part of the deposition file at all. (If SAXS, then deleting the nmr spectrometer should actually remove it, not just set those tags to '.')

I think we should probably discuss this more in person. It's a pretty technical topic to discuss via text.

**Comment by dmaziuk** [comment]
> You can't allow them to delete a "mandatory" section - unless you just immediately re-create the saveframe, but without values. (More of a "wipe" than a delete.)

Why not, it's not my business to tell you how you edit your entry. All I need is to not let you deposit an incomplete one. The rest of it is just to show you what's still incomplete without you having to hit the deposit button to find out. What's technical about this?

**Comment by jonwedell** [comment]
>  What's technical about this?

To be more precise, I think it's more productive to discuss in person. Otherwise we seem to get bogged down on minor technical details and waste a bunch of time typing back and forth when a 3 minute conversation would resolve it.

**Comment by elulrich** [comment]
I think until there is a change in policy from above my pay grade, BMRB 
is a database for NMR data. While other kinds of data might be deposited 
as supporting or corroborative or hybrid data, there should be some NMR 
data in every deposition to BMRB. This is why I made the NMR 
spectrometer mandatory. As I am writing this, the one exception might be 
theoretical NMR data, but even here there needs to be some way of 
designating field strength. This might be in the theoretical data sections.

**Comment by dmaziuk** [comment]
What's mandatory in a complete deposition is a separate issue, I think. In this one I fail to see why a user's ability to delete a saveframe requires a dictionary fix: ADIT lets you delete everything except entry information and natural and experimental source, with dictionary flags as they were. Why did that change in the first place?

**Comment by jonwedell** [comment]
@rsiegl  - this is "pending verification" again.

**Comment by rsiegl** [comment]
The Sample descriptions, software descriptions, NMR spectrometers and NMR experimental descriptions are all still deletable at all times (ie. when there is only present). Are these sections required for an entry? If they are not, then I can confirm this is fixed.

**Comment by jonwedell** [comment]
Indeed, those sections should be able to be deleted. (It's possible that the deposition only contains theoretical chemical shifts, for example, in which case none of those would be present.)
