### ISSUE TITLE
Verify Email 

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#129]
I had begun an entry from scratch after ending another session and it brought me to the molecular assembly page (I did not refresh the page or anything either).  I can access all of the sections, but when I click on the verify email section in the side bar it still shows the molecular assembly page. After I refreshed the page I could still access everything and the verify email page appears as it should. When I click the link in the email (not the verify one) it brings me to the verify your email page, but I can still access all the other sections from the side nav menu. It would not let me upload files though, so the locking of the document behavior seems to work. Allowing me to navigate around though probably should not be happening.

**Comment by jonwedell** [comment]
It was programmed this way (allowing viewing other sections before verification) so that we could make verifying an email optional until the final deposition step. I think I may actually change the behavior back that way, to allow automated deposition sessions to work.

Though returning to molecular assembly when starting a new deposition is a problem, indeed.
