### ISSUE TITLE
experiments under Assigned chemical shifts

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBdep#133]
Currently you can type anything you want in this field, yet it says "select from NMR experiment and samples list." I think this should be a drop down menu with all of the experiments from the experiment section as options. They currently only pop up as suggestions when typing. 

Additionally, is it necessary to have the "and samples list" part? I have yet to see an entry that has the sample included. This section also corresponds to the Experiment_name tag so it would not make sense if the sample were placed here.

**Comment by dmaziuk** [comment]
Original intent was:
- CS list is associated with experiment, sample, and conditions, so these were concatenated into a tuple that showed up in the drop-down list. That gets cleaned up in the post-processing so you'll never see it in the files.
- You can fill in the CS section before the other sections, in which case there's nothing to drop down. So you should be able to type stuff in instead.

**Comment by rsiegl** [comment]
That makes more sense. Thanks for clarifying Dimitri I'll close this issue then.

**Comment by dmaziuk** [comment]
I'm not sure you should: that was in ADIT where drop-downs are collected from multiple places and so on. I don't know if it's still true in the new interface. Maybe the wording should be changed to better match the interface etc.

**Comment by jonwedell** [comment]
Yes, as Dimitri mentioned I still need to implement some sort of special code to handle this tag by creating a tuple from the experiment loop. Eldon and I talked about this a lot today, but there really isn't any way around it without making a ton of dictionary changes.

**Comment by dmaziuk** [comment]
Can you do multi-select in drop-downs? It would be cute if you could list experiments, samples, and conditions in e.g. 3-column list with checkboxes and have them check one from each column.

**Comment by jonwedell** [comment]
Do you mean for `_Chem_shift_experiment.Experiment_name`? Yeah, perhaps I could implement something like this. But we already get the various fields linked together as a row in `_Experiment`, and I just need a way to link to the correct row. Or do you mean for entering data in the `_Experiment` loop?

**Comment by rsiegl** [comment]
`_Chem_shift_experiment.Experiment_name` is what I was referring to in this.

**Comment by dmaziuk** [comment]
In the simplest case you could let them select e.g. multiple software sections for the shifts from a single drop-down: much easier than having to create a separate row for each software used.

If that could be extended to multi-column selects, then yes: you need to link to the row in `_Experiment`, but you want to show them something they can recognize and experiment name alone is not enough. Same experiment could've been used on different samples and/or different conditions.

**Comment by jonwedell** [comment]
The experiment links are largely implemented (d566787, 5ead17c, 9504083) but right now only a demo exists for assigned chemical shifts, and there is still some work to be done.

First, when referencing an experiment, the ID tag needs to be visible in the interface, rather than the Name tag. (I will still show the name in the drop down, along with the sample and sample conditions) This allows a perfect link to the experiment, where experiment_name might not be a 1-1 correspondence if there are multiple experiments of the same type.

@elulrich - Is it reasonable for you to switch all of the `Experiment_name` tags to be hidden, and all the `Experiment_ID` tags to have whatever value was previously present in `Experiment_name`? And also add a prompt to the `Experiment_ID` tags, something like "Experiment description"? I might have to update some conditional rules as well.

My plan is to fill in the rest of the tags in the experimental linking loops (like _Chem_shift_experiment) on the deposition end, based on the values of the tag `Experiment_ID`. (Unless there is a tool to do this elsewhere in the pipeline already.)

**Comment by elulrich** [comment]
Hi,

Is this a deposition interface only implementation? Will the final 
NMR-STAR file have integer values for 'Experiment_ID'?

There is a real problem with this implementation, if the enumeration for 
'Experiment_ID' is to be a list of experiment names. Experiment_ID is an 
integer.

Sorry,
Eldon

**Comment by jonwedell** [comment]
Hey Eldon,

Specifically, I'm talking `_Chem_shift_experiment.Experiment_ID` (and it's brethren for other experiment types) showing up in the interface rather than `_Chem_shift_experiment.Experiment_name`. The user is presented with a list of the various experiment names, samples, and sample conditions as specified in the `Experiment` loop. When they choose one, the actual value stored in the tag `_Chem_shift_experiment.Experiment_ID` is the integer ID of the corresponding experiment. I can then use this to populate the `_Chem_shift_experiment.Experiment_name` and other `_Chem_shift_experiment` tags with the appropriate values.

As far as the actual enumeration, that doesn't change at all. Those are attached to the tag `_Experiment.Name` and I'm not changing that.

For an experiment saveframe that looks like this:

![Screenshot from 2019-04-22 14-53-53](https://user-images.githubusercontent.com/5184895/56524179-8eb9ce80-650e-11e9-913c-b530fe93adda.png)

they will see a list of options (I couldn't get a screenshot with the enumerations open, unfortunately) that when one is selected looks like this:

![Screenshot from 2019-04-22 14-55-43](https://user-images.githubusercontent.com/5184895/56524309-cb85c580-650e-11e9-86d0-668fd5eeada9.png)

**Comment by jonwedell** [comment]
> In the simplest case you could let them select e.g. multiple software sections for the shifts from a single drop-down: much easier than having to create a separate row for each software used.

I really like this idea, unfortunately it would be very complex to implement.

**Comment by elulrich** [comment]
Ok, I think I understand the what you are doing for the xxx.Experiment_ID tags and can make the changes in the dictionary file.

Selecting multiple software from a single drop down is appealing. The result in the interface should be separate rows. If the final presentation is some kind of single field with multiple software present separated by commas or some other separator and the field is editable, this is a recipe for disaster later in trying to parse and validate. We have been down that road with files sent to us from the PDB.

**Comment by elulrich** [comment]
BTW: Do I also need to change the enumeration ties in the dictionary for the xxx.Experiment_ID tags?

**Comment by dmaziuk** [comment]
> > In the simplest case you could let them select e.g. multiple software sections for the shifts from a single drop-down: much easier than having to create a separate row for each software used.
> 
> I really like this idea, unfortunately it would be very complex to implement.

Oh well... if you'd used multiple experiments for your assignments, I bet nobody's going to list them all if they have to manually add a row for each one. They'll just fill in the first one to make it turn green and move on.

**Comment by jonwedell** [comment]
> BTW: Do I also need to change the enumeration ties in the dictionary for the xxx.Experiment_ID tags?

No. I'm confused though, as it doesn't look like that tag had enumeration ties in the first place. Do you mean the enumeration ties for `Experiment_name`? If so, they don't **need** to be removed, as they will be hidden in the interface. But for sake of keeping things clean you could remove them.

**Comment by jonwedell** [comment]
> Oh well... if you'd used multiple experiments for your assignments, I bet nobody's going to list them all if they have to manually add a row for each one.

I now add three rows by default for these types of loops, so users should be more likely to realize they are expected to add all values, as they will have to delete at least 2 rows for the entry to become valid.


The implementation of this is complete. Upon deposition, `Experiment_name` will be populated based on the value of the tag `Experiment_ID`. The other tags in `Chem_shift_experiment` (and the other experimental loops) do not get populated, per Eldon.

**Comment by rsiegl** [comment]
Is this section supposed to say n/a?
![1](https://user-images.githubusercontent.com/44450691/56764622-c624b700-676a-11e9-9ec5-8c68106501c8.png)


If so then I can confirm this is fixed.

**Comment by jonwedell** [comment]
> Is this section supposed to say n/a?

No, but if that entry was started prior to the last dictionary update you would see that. A new entry should have the correct text.

**Comment by rsiegl** [comment]
I can confirm this is fixed.

**Comment by rsiegl** [comment]
Spoke too soon it would appear.

**Comment by rsiegl** [comment]
Since I cannot deposit any entries at the moment, I downloaded one using the developer tools. It would appear that the `_Chem_shift_experiment.Experiment_ID` behaves as it should, but the `_Experiment.ID` tag is missing in the experiment list loop.

![1](https://user-images.githubusercontent.com/44450691/56829427-4c073780-6829-11e9-9bb8-031a442f4343.png)



![2](https://user-images.githubusercontent.com/44450691/56829435-4f022800-6829-11e9-9a8e-641f931721fd.png)

**Comment by rsiegl** [comment]
Since we spoke about the screen shot I have above, I believe this issue is fixed. Not sure if you wanted to do anything more with it so I will leave it for you to close Jon.

**Comment by jonwedell** [comment]
Solved a while ago.
