### ISSUE TITLE
Add tracking of deleted saveframes, and a menu to un-delete them

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/BMRBDep#53]
Stop actually deleting them, and instead mark them as deleted. Then don't emit them during submission if deleted.

**Comment by rsiegl** [comment]
I can confirm that the deleting and restoring of the saveframes works. 

When a section is deleted the page says "No matching saveframes... that exists." You can still access this page by using the previous and next category buttons (the page still just says no matching saveframes etc.). I am not sure if we want to have it just skip over this page and onto the next saveframe or if we want to have a different page present. Just something I noticed while deleting saveframes.

**Comment by jonwedell** [comment]
Ah yeah, this behavior is somewhat buggy. I'll tweak it.

Do you think we should still show where a category would be, but say that it has been deleted and offer the option to restore? Or should we actually hide deleted sections, and force users to go to the restore menu to recover them?

**Comment by jonwedell** [comment]
The behavior should be more like what you expect now. It automatically redirects to the next category if you delete the last of a saveframe in a category.

**Comment by rsiegl** [comment]
Yeah I can confirm that works now. 

My initial thoughts on what to do with the deleted sections would be to make a sub-section under the Deposition Contents section (like the "Experimental descriptions" or the "NMR parameters") and title it "Deleted saveframes". This way the user could directly see all of the saveframes they have deleted rather than having to go into Deposition Options then Restore deleted saveframes then scroll through to find a desired saveframe that was deleted. This deleted saveframes sub-section could be used in the submission process as a final check (in the sense that the user would have to confirm their deletions prior to submitting the entry).
