### ISSUE TITLE
BMRB new testing system (bmrb 15000 as entry): NMR experiment descriptions>Experiment list

### ISSUE THREAD

**Issue by kcahya** [uwbmrb/BMRBDep#87]
Sample name found in bmrb15000 but selection needs to be fixed
Sample conditions name found in bmrb15000 selection needs to be fixed
NMR spectrometer name found in bmrb15000 selection needs to be fixed

**Comment by kcahya** [comment]
It works this time. However, for the sample name column, it's "Section not yet named: sample_1". Instead, it should be just "sample_1". For the sample condition column, it's "Section not yet named: sample_conditons_1". Instead it should be either "$unlabeled_sample" or "$selectively_labeled_sample". For NMR spectrometer name, it's "Section not yet named: NMR_spectrometer_1". Instead, there should be various choices such as $spectrometer_4 or $spectrometer_2.

**Comment by jonwedell** [comment]
It says "Section not named" because you haven't yet filled in a value for the `Name` tag for the saveframe category it links to. That is where you should enter the sf_framecode like we discussed. (There might not be a `Name` tag in older entries, so instead fill in that tag with the value of the `sf_framecode` tag.)

> Instead, there should be various choices such as $spectrometer_4 or $spectrometer_2.

Those will appear once you have created the appropriate spectrometer saveframes. To do that, go to "NMR Spectrometer" on the navigation menu, and click `Duplicate` or `Create new` and populate the saveframes with the data from the entry. Then, if you return to the NMR experiment descriptions section you will see them as options.

If you go start to finish in the new deposition system, you shouldn't encounter the "Section not named" message. Do you think that message could have a more clear description of what is the problem?

Finally, the new system will not show the "$" character at the start of a reference to another saveframe, but that is the expected behavior.

**Comment by dmaziuk** [comment]
I suspect the reason we never needed the "name" tags for most saveframes is because 90+% of the users submit a single sample, single conditions, single instrument entry. I think ADIT-NMR just names the first saveframe "sample", "sample_conditions", "spectrometer", and most users never even see any of it.

Just fill in $category_$local_id and anyone who cares can rename them later.

**Comment by jonwedell** [comment]
> Just fill in $category_$local_id and anyone who cares can rename them later.

Sure, I'll pre-fill them with the same values as the sf_framecode except with underscores replaced with spaces and they can change them if they wish.
