### ISSUE TITLE
BMRB new testing system (bmrb 15000 as entry): NMR experiment details>NMR timedomain data and other files

### ISSUE THREAD

**Issue by kcahya** [uwbmrb/BMRBDep#88]
Name of a file or directory not found in bmrb15000 and selection needs to be fixed

**Comment by jonwedell** [comment]
I don't believe this is a problem with the deposition system, as you are allowed to leave that saveframe blank if there is no data in that entry. Are you getting an error in that section, or are you just reporting that entry 15000 has no data to enter for it?

**Comment by kcahya** [comment]
Yes, these are white blanks. However, the keyword for "NMR timedomain data and other files" cannot be found in the bmr15000 file. Moreover, the selection didn't work for that particular column. If the keyword cannot be found, does it mean that there is no entry?

**Comment by rsiegl** [comment]
I think I understand your issue correctly. If an entry does not have a section that is included in the BMRBDep that we are testing, it is most likely because that entry is older and those sections were not implemented yet. If that is the case then you can just leave those sections blank when test depositing.
