### ISSUE TITLE
Two vertical scroll bars

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#95]
On any given page that you could scroll on there are two vertical scroll bars. One appears to be for the toolbar..? It spans the entire length of the page including the toolbar, but you can only scroll slightly. The second is for the body of the page and allows you to scroll down the page how you would expect. 

I am not sure if this is necessarily an issue, but it is something curious I noticed today.

**Comment by jonwedell** [comment]
I think I know what you mean, but for graphical glitches like this it would be particularly helpful if you could take a screenshot and attach it to the issue here. I don't believe my machine has the same problem, and I think it is screen resolution/browser dependent. Without seeing it it is hard to know for sure what is wrong.

Holding shift and pressing the "Print Key" button should let you take an image of a custom selected portion of the screen, or holding alt and pressing "Print Key" will take a screenshot of the entire browser window. The files save in your home directory and then you can attach them here.

**Comment by rsiegl** [comment]
![screenshot at 2019-02-12 14-37-22](https://user-images.githubusercontent.com/44450691/52666436-e9fa8f80-2ed3-11e9-9abe-3721a273a1c2.png)
![screenshot at 2019-02-12 14-38-03](https://user-images.githubusercontent.com/44450691/52666437-e9fa8f80-2ed3-11e9-90f6-0efd8d81d406.png)
Sorry about that, but here is the view of the double scroll bar as well as the toolbar one on its own. The browser I noticed this in was Firefox. I can check other browsers for this issue once we fix it as well.

**Comment by jonwedell** [comment]
Thanks, that is different than what I had pictured. That's definitely an issue to be fixed, though it should be some fairly minor CSS tweaks. Thanks!

**Comment by jonwedell** [comment]
I can't reproduce this in Firefox, so it must also be resolution dependent. Next time you're in the office if I could check a few things on your computer that would help me sort this out.

**Comment by rsiegl** [comment]
I was just messing around with the CSS. I think the html and body sections may be inheriting the scroll bar from some place. I think that because body does not even have an overflow line yet it seems to behave as if there was overflow set to auto. Also nothing changes when you remove the overflow line in the html section (overflow: auto;).

I set the overflow in the html section to hidden to stop it from appearing (since the scroll bar that is always present goes the whole html and not just the body). This fixed the issue for me. It removed the unnecessary scroll bar, retained a scroll bar where necessary and did not mess with the page height. 

I have not found any adverse effects yet, but I will leave this open until you or someone confirms this was the correct change.

**Comment by rsiegl** [comment]
I can confirm there is only one scroll bar now and it only appears when necessary.
